### ISSUE TITLE
图形的endpoint不支持Variables传入，只能选择固定服务器展示

### ISSUE THREAD

**Issue by 84372051** [n9e/grafana-n9e-datasource#1]
服务器比较多的话加载图形比较耗资源，且不容易搜索服务器

**Comment by jsers** [comment]
@84372051 
目前支持三种动态值:
=all 动态全选
=+{include} 动态包含
=-{exclude} 动态排除

![image](https://user-images.githubusercontent.com/7424634/83369834-22d3b600-a3f0-11ea-8f8c-d69759a58151.png)

**Comment by 84372051** [comment]
![QQ图片20200601105450](https://user-images.githubusercontent.com/45719547/83371987-9d9fcf80-a3f6-11ea-88fe-1a4663f4486d.png)

一次只展示一个主机的数据，通过变量来控制endpoint，不知道这种变量如何能传进去

**Comment by jsers** [comment]
v1.1.0 endpoints 支持 Grafana 的变量配置，暂时只开放 endpoints

**Comment by jsers** [comment]
![image](https://user-images.githubusercontent.com/7424634/83384640-427fd400-a41a-11ea-81b3-49c85a6fb2ec.png)
