### ISSUE TITLE
离线安装插件出现问题我不知道原因

### ISSUE THREAD

**Issue by supervisoredis** [n9e/grafana-n9e-datasource#10]
报错如下：
Error: Object prototype may only be an Object or null: undefined Evaluating http://xx.xx.xx.xx:3000/public/plugins/n9e-datasource/module.js Loading plugins/n9e-datasource/module

**Comment by jsers** [comment]
感觉是 grafana 版本问题，grafana 必须是 v7 版本

**Comment by ILOVEQIUXIAOYI** [comment]
7.5
