### ISSUE TITLE
保存数据源时{"err":"unauthorized"}

### ISSUE THREAD

**Issue by zhouxw536** [n9e/grafana-n9e-datasource#12]

**Comment by jsers** [comment]
配置数据源的时候没有填写正确的 token

**Comment by zhouxw536** [comment]
token是正确的，夜莺版本是V3.0，前端填写token后，并没有带到请求里

**Comment by jsers** [comment]
使用 v1.5.1 版本的，在数据源配置页面手动切换再选择下版本（这个版本的插件选择版本这块默认值有问题）
或者可以直接更新到 v1.5.3 版本
