### ISSUE TITLE
v2+grafana  token设置问题

### ISSUE THREAD

**Issue by y-andybaba** [n9e/grafana-n9e-datasource#13]
v3版本个人中心可设置token。v2版本自行生成token需配置在服务器哪个目录下。谢谢老哥
![image](https://user-images.githubusercontent.com/67846787/101709177-f947c580-3ac9-11eb-9e21-1595145441e6.png)

**Comment by y-andybaba** [comment]
v2版+grafana。grafana.log输出如下。这url无法访问。
t=2020-12-10T09:44:48+0800 lvl=info msg=Requesting logger=data-proxy-log **url=http://xxxxxxxxx/v1/portal/tree**
t=2020-12-10T09:44:48+0800 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/v1/portal/tree status=404 remote_addr=xxxxx time_ms=22 size=162 referer=http://xxxxxx:3000/datasources/edit/1/

设置为v3，url   http://xxxxxxx:81/api/rdb/tree。可以通。

是我设置的有问题吗？大佬。麻烦指导指导。我目前有两套环境。v2 和 v3

**Comment by jsers** [comment]
可以看下  readme 历史
![image](https://user-images.githubusercontent.com/7424634/101885678-685e1080-3bd5-11eb-805a-dbe67c549820.png)

**Comment by weizhenqian** [comment]
夜莺V2.7，grafana V7.5 /rdb/personnel-info/profile 文件不存在呀

**Comment by jsers** [comment]
这有有点久远，可以看下上面的截图，夜莺 v2 应该是在 monapi.yml 里面自己设置 token

Wisdom ***@***.***> 于2022年3月17日周四 17:38写道：
