### ISSUE TITLE
[BUG]添加数据源时显示不受信任

### ISSUE THREAD

**Issue by nondevops** [n9e/grafana-n9e-datasource#5]
使用版本:
grafana-7.0.3
n9e 最新版

问题现象:
前置条件都已准备到位,添加数据源之前在数据源列表搜索后显示该数据源不受信任;
添加数据源时,一直在转圈圈没有进入到配置界面;
点浏览器后退再刷新又可以进配置界面.

一直刷新界面:
![image](https://user-images.githubusercontent.com/12181410/85137941-8a08bb80-b274-11ea-98dd-84c147b21082.png)

grafana 添加n9e 数据源报错截图:
![image](https://user-images.githubusercontent.com/12181410/85137487-e5867980-b273-11ea-82b1-1a1f94e9e6c6.png)

**Comment by jsers** [comment]
unsigned 标签是因为没有提交到官方的 repo 里就会提示这个（提交比较麻烦而且审核的周期也长），但是不影响使用。
刚我试了下 grafana v7.0.3 + n9e-datasource v1.2.1 是没问题的。
你可以打开浏览器开发者工具看下有什么错误吗？
