### ISSUE TITLE
带下一级选项的监控项目无法使用变量，比如disk的mount，我net的iface

### ISSUE THREAD

**Issue by hagic-hhj** [n9e/grafana-n9e-datasource#6]
如题，磁盘监控和网络流量等监控项目，这些具有下一级tag的监控项，在grafana不能使用变量，只能使用确定endpoint，才能展示。
另外，数据源插件module.js文件太大了，用户体验不好～
忘修复，谢谢～

**Comment by jsers** [comment]
使用 endpoints 变量导致 tags 显示异常的问题 v1.3.1 版本已修复。
插件体积这个问题做了一次优化，体积缩减到之前的一半左右，目前仍未压缩代码，是因为使用官方的 grafane/toolkit 压缩代码以后使用会报错，暂时没有时间去排查原因，可以在 grafana server 里面把 gzip 打开也会进一步缩减体积。

**Comment by AstonPudding** [comment]
我好想也遇到了这个问题，但是不太确定现在使用的版本，如何查看datasource的版本呢
