### ISSUE TITLE
前端渲染很慢

### ISSUE THREAD

**Issue by yunweiboy** [n9e/grafana-n9e-datasource#7]
主机100台以上 就会渲染很慢  请求接口数据都保持在毫秒级别...

**Comment by jsers** [comment]
这是 grafana 内置绘图组件的瓶颈，没有对数据量相对比较大的场景做优化，n9e 的看图会稍微好一点。
浏览器的渲染也会受限于客户端的cpu和内存性能，最终都会有个上限。
可以适当的开启聚合，理论上肉眼看上百台机器的线（可能都成"面"）是没有太大意义的。
