### ISSUE TITLE
在grafana添加数据源时候，出现bad gateway，找不到原因

### ISSUE THREAD

**Issue by u31s** [n9e/grafana-n9e-datasource#9]
在grafana添加数据源时候，出现bad gateway，找不到原因
![n9e1](https://user-images.githubusercontent.com/19942704/89606822-963bed00-d8a3-11ea-98df-a98ef371a744.png)

_Originally posted by @u31s in https://github.com/n9e/grafana-n9e-datasource/issues/2#issuecomment-670305587_

**Comment by UlricQin** [comment]
URL后面配置nginx地址，http开头，如果有问题，基本就是nginx本身配置的有问题
